##############################################
#                                            #
# HYPRLAND config by Gabe <Gabriel-Grechuk>. #
#                                            #
##############################################


## VARIABLES.
### Colors.
$active_border_color=0xaa534293       #544293
$inactive_border_color=0x88918983     #918983
$group_border_color=0xaa05bbaa        #05bbaa
$active_group_border_color=0xaaeb5951 #eb5951

### Files.
$wallpaper=/home/gabe/Imagens/Wallpapers/WindowCat.png

### Apps.
$term=alacritty
$menu=wofi --show drun -o DP-3
$browser=MOZ_ENABLE_WAYLAND=1 firefox
$filemanager=$term -e xplr
$editor=$term -e nvim
$chat=discord
$music=$term -e cava & $term -e ncmpcpp
$lock=swaylock -f -e -l -L -s fill -i $wallpaper
$suspend=swaylock -f -e -l -L -s fill -i $wallpaper && sleep 2 && systemctl suspend



## MONITOR CONFIGS.
monitor=,1366x768@60,0x0,1
workspace=DP-1,1



## GENERAL WM CONFIG.
general {
    sensitivity=1.0
    main_mod=ALT

    gaps_in=5
    gaps_out=15

    border_size=3
    col.active_border=$active_border_color
    col.inactive_border=$inactive_border_color

    apply_sens_to_raw=0

    damage_tracking=full
}



## MOUSE AND KEYBOARD CONFIG.
input {
    kb_layout=br
    kb_variant=abnt2
    kb_model=
    kb_options=
    kb_rules=

    follow_mouse=1
}



## NICE WINDOW CONFIG.
decoration {
    rounding=5
    blur=1
    blur_size=6
    blur_passes=1
}

animations {
    enabled=1
    animation=windows,1,7,default
    animation=borders,1,7,default
    animation=fadein,1,7,default
    animation=workspaces,1,7,default
}

### Really nice, but instable; Sometimes it may crash the wm.
dwindle {
    pseudotile=0
    col.group_border=$group_border_color
    col.group_border_active=$active_group_border_color
}



## WINDOWS RULES.
windowrule=opacity 0.9 0.8,Alacritty

### Spawn Apps.
bind=ALTSHIFT,return,exec,alacritty
bind=SUPER,D,exec,$menu
bind=SUPER,E,exec,$filemanager
bind=SUPER,F,exec,$browser
bind=SUPER,C,exec,$chat
bind=SUPER,M,exec,$music
bind=SUPER,N,exec,$editor
bind=SUPERSHIFT,L,exec,$lock
bind=SUPERSHIFT,S,exec,$suspend

### Window operations.
bind=ALTSHIFT,Q,killactive,
bind=ALTSHIFT,E,exit,
bind=ALT,SPACE,togglefloating,
bind=ALT,G,togglegroup,
bind=ALT,C,changegroupactive,
bind=ALT,S,togglesplit,
bind=ALT,P,pseudo,
bind=ALT,F,fullscreen,

### Focusing the window.
bind=ALT,H,movefocus,l
bind=ALT,L,movefocus,r
bind=ALT,K,movefocus,u
bind=ALT,J,movefocus,d



## WORKSPACES CONFIGS.
### Select a workspace.
bind=ALT,1,workspace,1
bind=ALT,2,workspace,2
bind=ALT,3,workspace,3
bind=ALT,4,workspace,4
bind=ALT,5,workspace,5
bind=ALT,6,workspace,6
bind=ALT,7,workspace,7
bind=ALT,8,workspace,8
bind=ALT,9,workspace,9
bind=ALT,0,workspace,10

### Move the windo to a workspace.
bind=ALTSHIFT,exclam,movetoworkspacesilent,1 # When using shift, it needs to process the resultant symbol.
bind=ALTSHIFT,at,movetoworkspacesilent,2
bind=ALTSHIFT,numbersign,movetoworkspacesilent,3
bind=ALTSHIFT,dollar,movetoworkspacesilent,4
bind=ALTSHIFT,percent,movetoworkspacesilent,5
bind=ALTSHIFT,asciicircum,movetoworkspacesilent,6
bind=ALTSHIFT,ampersand,movetoworkspacesilent,7
bind=ALTSHIFT,asterisk,movetoworkspacesilent,8
bind=ALTSHIFT,parenleft,movetoworkspacesilent,9    # NOTE: 'paren' not 'parent'.
bind=ALTSHIFT,parenright,movetoworkspacesilent,10  # NOTE: 'paren' not 'parent'. Just fallback binds for keys

## FallbaFallback values.
#bind=ALTCONTROL,1,movetoworkspace,1
#bind=ALTCONTROL,2,movetoworkspace,2
#bind=ALTCONTROL,3,movetoworkspace,3
#bind=ALTCONTROL,4,movetoworkspace,4
#bind=ALTCONTROL,5,movetoworkspace,5
#bind=ALTCONTROL,6,movetoworkspace,6
#bind=ALTCONTROL,7,movetoworkspace,7
#bind=ALTCONTROL,8,movetoworkspace,8
#bind=ALTCONTROL,9,movetoworkspace,9
#bind=ALTCONTROL,0,movetoworkspace,10



## EXEC.
exec-once=swaybg -i $wallpaper
exec-once=swaync
exec-once=nm-applet --indicator
exec-once=blueman-applet

